import { customAlphabet } from 'nanoid';

export default {
	/* User */

	USER_NAME_MAX_LENGTH: 30,
	USER_EMAIL_MAX_LENGTH: 50,
	USER_PASSWORD_MIN_LENGTH: 8,

	/* QueueRoom */

	QROOM_NAME_MAX_LENGTH: 100,
	QROOM_DESCRIPTION_MAX_LENGTH: 1000,
	QROOM_MAX_CAPACITY: 256,
	QROOM_CODE_LENGTH: 5,
	QROOM_CODE_ALPHABET: '1234567890',

	/* QueueEntry */

	QENTRY_TOPIC_MAX_LENGTH: 80,

	/* Miscellaneous */

	MONGO_DUPLICATE_KEY_ERROR: 11000,
};
