export default {
    USER_NAME_MAX_LENGTH: 30,
    USER_EMAIL_MAX_LENGTH: 50,
    USER_PASSWORD_MIN_LENGTH: 8,

    QROOM_NAME_MAX_LENGTH: 100,
	QROOM_DESCRIPTION_MAX_LENGTH: 1000,
	QROOM_MAX_CAPACITY: 256,

    QENTRY_TOPIC_MAX_LENGTH: 80,
};
